### ISSUE TITLE
🚲 Test Server

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#1094]
# Description

Improve Test Server usability improvements and bugs

# Core objectives

Test Server provides a simplified fast im-memory implementation of Temporal Server API with additional features provided for testing only like time-skipping. This Epic tracks the tasks related to the improvement of the Test Server itself that don't affect Java SDK.

# Tasks

- [ ] temporalio/sdk-java#1079
- [ ] temporalio/sdk-java#1093
- [ ] temporalio/sdk-java#1069
- [x] temporalio/sdk-java#84
- [ ] temporalio/sdk-java#1139
- [x] temporalio/sdk-java#1158
- [x] temporalio/sdk-java#1220
- [x] temporalio/sdk-java#1221
- [x] temporalio/sdk-java#1223 
- [ ] temporalio/sdk-java#262
- [ ] temporalio/sdk-java#1403
- [ ] #1642
- [x] #1682 
- [x] #1746
- [x] #1742
- [x] #1692
- [ ] #1693

# Bugs

- [ ] temporalio/sdk-java#1291
- [x] temporalio/sdk-java#1288
- [x] temporalio/sdk-java#1289 
- [x] temporalio/sdk-java#1319
- [x] temporalio/sdk-java#1398
- [x] temporalio/sdk-java#1401 
- [ ] temporalio/sdk-java#1138
- [x] temporalio/sdk-java#1424
- [x] temporalio/sdk-java#1425
- [ ] temporalio/sdk-java#1426
- [x] temporalio/sdk-java#1427 
- [ ] temporalio/sdk-java#1429 
- [ ] #1618
- [x] #1903

# Add implementation for endpoints

**WorkflowService**

- [ ] registerNamespace
- [x] describeNamespace
- [ ] listNamespaces
- [ ] updateNamespace
- [ ] deprecateNamespace
- [ ] getWorkflowExecutionHistoryReverse
- [ ] resetWorkflowExecution
- [ ] #1693
- [ ] listArchivedWorkflowExecutions
- [ ] scanWorkflowExecutions
- [ ] countWorkflowExecutions
- [ ] getSearchAttributes
- [ ] resetStickyTaskQueue
- [ ] describeTaskQueue
- [ ] getClusterInfo
- [x] getSystemInfo
- [ ] listTaskQueuePartitions

**OperatorService**

- [ ] listSearchAttributes

**Comment by cretz** [comment]
Edited description to remove https://github.com/temporalio/sdk-core/issues/426, but it also qualified the names of all issues too, sorry!

**Comment by Quinn-With-Two-Ns** [comment]
Closing since we no longer want to use GH issues as epics

**Comment by Quinn-With-Two-Ns** [comment]
Closing since we no longer want to use GH issues as epics
