### ISSUE TITLE
Revisit ActivityExecutionContext and ActivityCompletion clients

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#752]
Code quality and readability around `ActivityExecutionContext`, `ActivityCompletionClient`, `ManualActivityCompletionClient` requires refactoring to make code more maintainable. 

- [x] #943 
- [x] Manual Completion Client is a public user-facing interface that is undocumented. #1181
- [ ] Errors handling around heartbeating in ActivityExecutionContext and ManualActivityCompletionClient are different without apparent reasons.
- [x] #1233
- [ ] In case of some exceptions, ActivityExecutionContext stops heartbeating.
- [ ] ActivityExecutionContext#heartbeat and other methods like that should have a short explanation about the heartbeat throttling
- [ ] #1354

**Comment by Spikhalskiy** [comment]
`ActivityExecutionContext` is done

**Comment by Quinn-With-Two-Ns** [comment]
Closing since we no longer want to use GH issues as epics
