### ISSUE TITLE
OpenTracing context is not propagated in some cases

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#922]
- [x] Child workflows as reported in comments in #537
- [x] Async invocation of a function or procedure as lambda (works if we invoke a stub method reference, like `Async.function(activityStub:activityMethod)`), see #537 too
- [x] `continueAsNew` needs a proper wiring of headers and OT implementation #844
- [ ] signal methods (headers on these methods are recently implemented) #1306
